<Project Sdk="Microsoft.NET.Sdk.WebAssembly">
  <Import Project="../../src/Umsatzschaetzung.Browser/Browser.props" />
  <PropertyGroup>
    <RootNamespace>Umsatzschaetzung.Lessons</RootNamespace>
    <InvariantGlobalization>false</InvariantGlobalization>
    <BlazorIcuDataFileName>icudt_EFIGS.dat</BlazorIcuDataFileName>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../../src/Umsatzschaetzung.Browser/Umsatzschaetzung.Browser.csproj" />
    <Compile Include="../headless/Targets.cs" />
    <Compile Include="../headless/Steps.cs" />
  </ItemGroup>

  <Import Project="../../src/Umsatzschaetzung.Browser/Browser.targets" />
</Project>
