<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows10.0.19041.0</TargetFramework>
    <SupportedOSPlatformVersion>10.0.19041.0</SupportedOSPlatformVersion>
    <RootNamespace>Ausbeute.App</RootNamespace>
    <AssemblyName>ausbeute</AssemblyName>
    <UseWPF>true</UseWPF>
    <InvariantGlobalization>false</InvariantGlobalization>
    <EnableWindowsTargeting>true</EnableWindowsTargeting>
    <RuntimeIdentifiers>win-x64;win-arm64</RuntimeIdentifiers>
    <ApplicationManifest>app.manifest</ApplicationManifest>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../Ausbeute.Core/Ausbeute.Core.csproj" />
    <ProjectReference Include="../Ausbeute.Llama/Ausbeute.Llama.csproj" />
    <PackageReference Include="Microsoft.Web.WebView2" Version="1.0.3485.44" />
  </ItemGroup>
</Project>
