<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <RootNamespace>Umsatzschaetzung</RootNamespace>
    <ModelSet>text</ModelSet>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../Umsatzschaetzung.Core/Umsatzschaetzung.Core.csproj" />
    <ProjectReference Include="../Umsatzschaetzung.Nets/Umsatzschaetzung.Nets.csproj" />
  </ItemGroup>
  <ItemGroup>
    <InternalsVisibleTo Include="eval" />
    <InternalsVisibleTo Include="Umsatzschaetzung.Tests" />
  </ItemGroup>
  <Import Project="../../Models.targets" />
</Project>
