<Project Sdk="Microsoft.NET.Sdk.WebAssembly">
  <Import Project="../Umsatzschaetzung.Browser/Browser.props" />
  <PropertyGroup>
    <RootNamespace>Umsatzschaetzung.Web</RootNamespace>
    <RunAOTCompilation Condition="'$(Configuration)' == 'Release'">true</RunAOTCompilation>
    <PublishTrimmed Condition="'$(Configuration)' == 'Release'">true</PublishTrimmed>
    <TrimMode>partial</TrimMode>
    <SuppressTrimAnalysisWarnings>true</SuppressTrimAnalysisWarnings>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../Umsatzschaetzung.Browser/Umsatzschaetzung.Browser.csproj" />
  </ItemGroup>

  <Import Project="../Umsatzschaetzung.Browser/Browser.targets" />

  <Target Name="PublishHtaccess" AfterTargets="Publish">
    <Copy SourceFiles="htaccess" DestinationFiles="$(PublishDir)wwwroot/.htaccess" SkipUnchangedFiles="true" />
  </Target>
</Project>
